# Generated by Django 5.1.4 on 2026-02-25 12:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="last name"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("manager", "Manager"),
                            ("staff", "Staff"),
                        ],
                        default="staff",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "desired_hours_per_week",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Staff's preferred weekly hours. Used for fairness analytics only; does not constrain scheduling directly.",
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("notify_in_app", models.BooleanField(default=True)),
                ("notify_email", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Skills this staff member is certified to perform.",
                        related_name="staff_members",
                        to="accounts.skill",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="StaffAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recurrence",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly (recurring)"),
                            ("one_off", "One-off (specific date)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="0=Monday, 6=Sunday. Only for weekly recurrence.",
                        null=True,
                    ),
                ),
                ("specific_date", models.DateField(blank=True, null=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="Timezone in which start_time/end_time were entered (e.g., America/Los_Angeles).",
                        max_length=50,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional note (e.g., 'School pickup at 3pm')",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"role": "staff"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_windows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Availability",
                "verbose_name_plural": "Staff Availability Windows",
                "ordering": ["recurrence", "day_of_week", "specific_date"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("recurrence", "weekly")),
                        fields=("user", "recurrence", "day_of_week"),
                        name="unique_weekly_availability_per_day",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("recurrence", "one_off")),
                        fields=("user", "recurrence", "specific_date"),
                        name="unique_one_off_availability_per_date",
                    ),
                ],
            },
        ),
    ]
