# Generated by Django 5.1.4 on 2026-02-25 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "headcount_needed",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Number of staff required for this shift."
                    ),
                ),
                (
                    "start_utc",
                    models.DateTimeField(help_text="Shift start time in UTC."),
                ),
                (
                    "end_utc",
                    models.DateTimeField(
                        help_text="Shift end time in UTC (may cross midnight)."
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Published shifts are visible to assigned staff.",
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "edit_cutoff_hours",
                    models.PositiveSmallIntegerField(
                        default=48,
                        help_text="Hours before shift start after which the shift is locked from edits.",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_shifts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shifts",
                        to="locations.location",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_shifts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "required_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shifts",
                        to="accounts.skill",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shift",
                "verbose_name_plural": "Shifts",
                "ordering": ["start_utc"],
            },
        ),
        migrations.CreateModel(
            name="ShiftAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("swap_pending", "Swap/Drop Pending"),
                            ("covered", "Covered (swap out)"),
                            ("dropped", "Dropped"),
                        ],
                        default="assigned",
                        max_length=15,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="scheduling.shift",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Shift Assignment",
                "verbose_name_plural": "Shift Assignments",
            },
        ),
        migrations.CreateModel(
            name="ManagerOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "constraint_violated",
                    models.CharField(
                        help_text="Identifier of the constraint that was overridden (e.g., 'consecutive_days_7').",
                        max_length=100,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Manager's documented reason for the override."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides",
                        to="scheduling.shiftassignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manager Override",
                "verbose_name_plural": "Manager Overrides",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SwapRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("swap", "Shift Swap"),
                            ("drop", "Drop / Open Pickup"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_acceptance", "Awaiting Staff B Acceptance"),
                            ("pending_pickup", "Open for Pickup"),
                            ("pending_manager", "Awaiting Manager Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="pending_acceptance",
                        max_length=20,
                    ),
                ),
                ("requester_note", models.TextField(blank=True)),
                ("manager_note", models.TextField(blank=True)),
                ("target_accepted_at", models.DateTimeField(blank=True, null=True)),
                ("manager_reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Auto-calculated for drops; null for manager-only expiry.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_requests",
                        to="scheduling.shiftassignment",
                    ),
                ),
                (
                    "claimed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drops_claimed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="swap_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="swap_requests_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Swap Request",
                "verbose_name_plural": "Swap Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(
                fields=["location", "start_utc"], name="scheduling__locatio_c52473_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(
                fields=["start_utc", "end_utc"], name="scheduling__start_u_5fc4cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shiftassignment",
            index=models.Index(
                fields=["user", "shift"], name="scheduling__user_id_ff3747_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shiftassignment",
            index=models.Index(fields=["status"], name="scheduling__status_76abf1_idx"),
        ),
        migrations.AddConstraint(
            model_name="shiftassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["assigned", "swap_pending"])),
                fields=("shift", "user"),
                name="unique_active_assignment_per_shift",
            ),
        ),
        migrations.AddIndex(
            model_name="swaprequest",
            index=models.Index(fields=["status"], name="scheduling__status_29c90f_idx"),
        ),
        migrations.AddIndex(
            model_name="swaprequest",
            index=models.Index(
                fields=["requester", "status"], name="scheduling__request_4b4f6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="swaprequest",
            index=models.Index(
                fields=["expires_at"], name="scheduling__expires_6800a9_idx"
            ),
        ),
    ]
