# Generated by Django 5.1.4 on 2026-02-25 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True,
                        help_text="Dot-separated action identifier, e.g., 'shift_assignment.created'",
                        max_length=100,
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField(null=True)),
                (
                    "before",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Serialized state of the object before the change. Empty for creations.",
                    ),
                ),
                (
                    "after",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Serialized state of the object after the change. Empty for deletions.",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log Entry",
                "verbose_name_plural": "Audit Log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="audit_audit_content_4c2ead_idx",
                    ),
                    models.Index(
                        fields=["actor", "-created_at"],
                        name="audit_audit_actor_i_1175ab_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="audit_audit_action_0c6a84_idx",
                    ),
                ],
            },
        ),
    ]
