# Generated by Django 5.1.4 on 2026-02-25 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("shift_assigned", "Shift Assigned"),
                            ("shift_changed", "Shift Changed"),
                            ("shift_published", "Schedule Published"),
                            ("swap_request_received", "Swap Request Received"),
                            ("swap_accepted", "Swap Accepted by Staff"),
                            ("swap_approved", "Swap Approved by Manager"),
                            ("swap_rejected", "Swap Rejected"),
                            ("swap_cancelled", "Swap Cancelled"),
                            ("drop_available", "Open Shift Available for Pickup"),
                            ("drop_claimed", "Your Dropped Shift Was Claimed"),
                            ("swap_approval_needed", "Swap Awaiting Your Approval"),
                            ("overtime_warning", "Overtime Warning"),
                            ("availability_changed", "Staff Availability Updated"),
                            ("schedule_conflict", "Concurrent Edit Conflict"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("data", models.JSONField(blank=True, default=dict)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="notificatio_recipie_4e3567_idx",
                    ),
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="notificatio_recipie_a972ce_idx",
                    ),
                ],
            },
        ),
    ]
